### ISSUE TITLE
Use standalone framework instead of jQuery?

### ISSUE THREAD

**Issue by highslide-software** [soldair/highcharts-browserify#18] opened 2015-10-19 11:51 UTC
> N.b. highcharts patches jQuery so please ensure your project uses the same version as highcharts-browserify so you do not have two versions in your node_modules folder.

If you use the Standalone Framework, you don't need jQuery.

**Comment by soldair** [comment] 2015-10-19 12:11
great thanks for the note. i would love to get this patched.

what do you think @achingbrain and @KenanY?

**Comment by achingbrain** [comment] 2015-10-19 12:18
I have nothing but anecdotal evidence but I'd imagine most people using this module would also be using jQuery so I'm not sure the standalone framework should be used instead of it, but it does makes sense to try to handle the case when jQuery isn't present.

I guess the jQuery dependency could be removed from this project, then wrap the instances of `require('jquery')` added by the gulpfile with a try/catch that requires the standalone framework if requiring jQuery fails.

**Comment by soldair** [comment] 2015-10-19 12:22
@highslide-software where do you stand on supporting node style modules (module.exports) in highcharts itself? or do you see this is a good place to have this shenanigans?

i see you have on official highcharts-release published to npm now but it doesnt provide a main!
```
$ npm install highcharts-release
highcharts-release@4.1.9 node_modules/highcharts-release
$ node
> require('highcharts-release')
Error: Cannot find module 'highcharts-release'
```

we should at least find a way to depend on this rather than manually bundling. but im interested in your thoughts

**Comment by highslide-software** [comment] 2015-10-19 13:25
@gvaartjes @jon-a-nygaard FYI.

@achingbrain Some years ago 80% of the Internet's websites used jQuery, but I think it is not that abundant today. 
![skjermbilde 2015-10-19 kl 15 21 31](https://cloud.githubusercontent.com/assets/227836/10578877/295aef32-7675-11e5-9b77-4f7280da46dc.png)

@soldair 
> where do you stand on supporting node style modules (module.exports) in highcharts itself?

We are working on this right now, also by providing a main.js with the right pointers.

**Comment by soldair** [comment] 2015-10-19 13:38
great. if you remember to let us know when it's up that would be great. i would strongly prefer to not have to maintain this packaging of your amazing work. ;)

**Comment by highslide-software** [comment] 2015-10-20 07:59
Thanks, will follow up!

**Comment by achingbrain** [comment] 2015-10-20 11:21
I've just submitted #19 which removes the jQuery dependency and also uses highcharts-release instead of having a copy of highcharts as part of this repo.

@highslide-software Granted the sample size is pretty small but at the time of writing, of the [18](https://github.com/search?utf8=%E2%9C%93&q=filename%3Apackage.json+highcharts-browserify) public repos on github that use highcharts-browserify, [14](https://github.com/search?utf8=%E2%9C%93&q=filename%3Apackage.json+highcharts-browserify+jquery&type=Code&ref=searchresults) of them also depend on jQuery.

Nevertheless if `highcharts-release` supported `require`/`module.exports` that would be amazing and this module would not be necessary.  I am most definitely a fan of less code.

**Comment by soldair** [comment] 2015-10-20 16:32
ok. merged. landed on npm in 2.0.0

**Closed by soldair** 2015-10-20 16:32 UTC

**Comment by justin808** [comment] 2015-11-11 09:18
@soldair @achingbrain How do I get this latest version to play with the older syntax of having highcharts on top of jQuery? I'm using webpack.

**Comment by soldair** [comment] 2015-11-11 12:17
Hey im a webpack newb but..
if your project also depends on jquery you should be able to require it and use it like the example.
hquery would need to come from the jquery module `npm install jquery` rather than highcharts-browserify including it's own arbitrary version.

**Comment by justin808** [comment] 2015-11-11 18:35
I've got jquery in webpack, and I'm trying to require it before HighCharts. The issue I'm seeing is:

```
     var cg, chartSize;
      cg = $("#correlation-graph");
      if (cg.length > 0 && cg.highcharts()) {
```

And then I get

Uncaught TypeError: cg.highcharts is not a function

So `$` does not have highcharts added.

How/Where does highcharts monkey patch jQuery?

**Comment by soldair** [comment] 2015-11-11 18:41
this is the function highcharts uses to extend jquery
https://github.com/highslide-software/highcharts-release/blob/master/highcharts.src.js#L975

**Comment by justin808** [comment] 2015-11-12 02:32
@soldair I did some debugging.

The problem is that if highcharts-standalone is loaded, which it is, then the jQuery binding never happens.

I'm working on code that is a combination of the old and new. 

And I'd like to only use npm for JS assets.

How do I proceed.

**Comment by justin808** [comment] 2015-11-12 02:44
I created a new issue for this, #21.
